### ISSUE TITLE
AttributeError 'NoneType' object has not attribute 'GetRootLayer'

### ISSUE THREAD

**Issue by DJT777** [j3soon/OmniIsaacGymEnvs-DofbotReacher#2]
I am getting an error in Step 3 saying "AttributeError 'NoneType' object has not attribute 'GetRootLayer'" when running the code from mniisaacgymenvs/utils/usd_utils/create_instanceable_dofbot.py in the script editor of Isaac Gym.

**Comment by DJT777** [comment]
The error I think was coming from not being able to access the Omniverse Nvidia files.

Solve by setting up a Nucleus account in the Omniverse app.

**Comment by j3soon** [comment]
Thank you for providing the solution!

This error is caused by not setting up Nucleus correctly. I'll update the README to clarify this in the future.
